<?php
namespace call\services\order;
/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


interface OrderServiceIf {
  /**
   * @return int
   */
  public function getOrderId();
  /**
   * @param int $orderId
   * @return \call\services\order\Order
   */
  public function orderInit($orderId);
  /**
   * @param int $id
   * @return bool
   */
  public function HasId($id);
}


